
//weather
const weather = {
    REQUEST_WEATHER_SAGA: '@SAGA/REQUEST_WEATHER',
    REQUEST_WEATHER_SUCCESS: '@REQUEST_WEATHER_SUCCESS',
    REQUEST_WEATHER_FAILED: '@REQUEST_WEATHER_FAILED',
};

export default {
    weather
}